name: Deploy pages

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.12.1"

      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          ls -l

      - name: Build for All subfolders
        run: |
          cd ${{ github.workspace }}
          ls -l
          for d in $(tree -d -L 1 | grep -v "build" | grep -v "directories"); do
            if [ -f "$d/package.json" ]; then
              echo "Building $d"
              cd $d
              npm install @slidev/cli @slidev/theme-default @slidev/theme-seriph
              npm i -D @iconify-json/twemoji
              npm i -D playwright-chromium
              npx slidev build --base /${{ github.event.repository.name }}/${d}
              npx slidev export --output ${{ github.workspace }}/${d}/dist
              cd ..
            fi
          done
          tree -d -L 2

      - name: Create build folder
        run: |
          mkdir -p build
          tree -d -L 2

      - name: Copy build files to root # */dist -> build/*
        run: |
          tree -d -L 2
          for d in $(tree -d -L 1 | grep -v "build" | grep -v "directories"); do
            if [ -d "$d/dist" ]; then
              echo "Copying $d"
              mkdir -p build/$d
              cp -r $d/dist/* build/$d
            fi
          done
          tree -d -L 2

      - name: Generate index.html
        run: |
          echo "<html><head><link href=\"/assets/css/style.css\" rel="stylesheet" type="text/css" /><title>Slides</title></head><body><h1>Slides Index</h1><ul>" > build/index.html
          for d in $(tree -d -L 1 | grep -v "build" | grep -v "directories"); do
            if [ -d "$d/dist" ]; then
              echo "<li><a href=\"./$d\">$d</a></li>" >> build/index.html
            fi
          done
          echo "</ul></body></html>" >> build/index.html

      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
