name: Deploy pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build for All subfolders
        run: ls -d */ | xargs -I {} sh -c "cd {} && npm install && npm i -g @slidev/cli && slidev build --base ${{ github.event.repository.name }}"

      - name: Create build folder
        run: |
          mkdir -p build
          tree -d -L 2

      - name: Copy build files to root # */dist -> build/*
        run: |
          for d in $(tree -d -L 1 | grep -v "build" | grep -v "directories"); do
            if [ -d "$d/dist" ]; then
              echo "Copying $d"
              mkdir -p build/$d
              cp -r $d/dist/* build/$d
            fi
          done

      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
